defaults: &defaults
  :cs_api:
    :challenges: 'http://cs-api-sandbox.herokuapp.com/v1/challenges'
    :categories: 'http://cs-api-sandbox.herokuapp.com/v1/categories'
    :members: 'http://cs-api-sandbox.herokuapp.com/v1/members'
    :key: ''
  :expiry: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults